DataSpace/DataSpace/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataSpace.Attributes;
using DataSpace.Data;
using DataSpace.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DataSpace.Controllers
{
    [AuthorizeAdmin]
    public class AdminController : Controller
    {
        private readonly SpaceContext _context;
        public AdminController( SpaceContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return RedirectToAction(nameof(Review));

            //var experiments = _context.Experiments.Include(e => e.Author).Include(e => e.LeadIstitution).Include(e => e.Mission);
            //return View(experiments.Where(p => p.EvaluationStatus == EvaluationStatus.Submitted).ToList());
        }
        public IActionResult Review()
        {
            var experiments = _context.Experiments.Include(e => e.Author).Include(e => e.LeadIstitution).Include(e => e.Mission);
            return View(experiments.Where(p => p.EvaluationStatus == EvaluationStatus.Submitted).ToList());

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var experiment = await _context.Experiments
                .Include(e => e.Author)
                .Include(e => e.LeadIstitution)
                .Include(e => e.Mission)
                .FirstOrDefaultAsync(m => m.ExperimentID == id);
            if (experiment == null)
            {
                return NotFound();
            }

            return View(experiment);
        }

        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var experiment = await _context.Experiments.FindAsync(id);
            if (experiment == null)
            {
                return NotFound();
            }
            experiment.EvaluationStatus = EvaluationStatus.Approved;
            _context.Update(experiment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Review));
        }
        public async Task<IActionResult> Reject(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var experiment = await _context.Experiments.FindAsync(id);
            if (experiment == null)
            {
                return NotFound();
            }
            experiment.EvaluationStatus = EvaluationStatus.Rejected;
            _context.Update(experiment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Review));
        }

        public IActionResult Accounts()
        {
            return Redirect("/Home/StatusCode/?code=103");
        }
    }
}

DataSpace/DataSpace/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataSpace.Data;
using DataSpace.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DataSpace.Controllers
{
    [Route("/Login")]
    public class LoginController : Controller
    {
        private readonly SpaceContext _context;

        public LoginController(SpaceContext context) => _context = context;

        public IActionResult Login() => View();

        private bool Verify(Login login, string password)
        {
            bool ret = login.Verify(password);
            _context.SaveChanges();
            return ret;
        }
        [HttpPost]
        public async Task<IActionResult> Login(string loginID, string password)
        {
            var login = await _context.Logins.FindAsync(loginID);
            if (login == null || !Verify(login, password))
            {
                if (login.BadAttempt < 2)
                    ModelState.AddModelError("LoginFailed", "Login failed, please try again.");
                else
                    ModelState.AddModelError("LoginFailed", "Account Locked!");

                return View(new Login { LoginID = loginID });
            }
            // Login customer.
            HttpContext.Session.SetInt32(nameof(Person.PersonID), login.PersonID);
            HttpContext.Session.SetString(nameof(Person.FirstName), login.Person.FirstName);
            if(login.Person.IsAdmin)
                HttpContext.Session.SetString(nameof(Person.FamilyName), login.Person.FamilyName);

            //TODO: redirect to submission page
            return RedirectToAction("Index", "Home");
        }
        [Route("LogoutNow")]
        public IActionResult Logout()
        {
            // Logout customer.
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

DataSpace/DataSpace/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataSpace.Data;
using DataSpace.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DataSpace.Controllers
{
    [DataSpace.Attributes.AuthorizeUser]
    public class UserController : Controller
    {
        private readonly SpaceContext _context;
        public UserController(SpaceContext context) => _context = context;
        private int PersonID => HttpContext.Session.GetInt32(nameof(Person.PersonID)).Value;

        public IActionResult Index()
        {
            var experiments = _context.Experiments.Include(e => e.Author).Include(e => e.LeadIstitution).Include(e => e.Mission);
            return View(experiments.Where(p => p.AuthorId == PersonID).OrderBy(p=>p.EvaluationStatus).ToList());
        }
        public async Task<IActionResult> Profile()
        {
            var person = await _context.People.FindAsync(PersonID);
            ViewData["InstitutionID"] = new SelectList(_context.Institutions, "ABN", "Name", person.InstitutionID);
            return View(person);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile([Bind("FirstName,FamilyName,Affiliation,City,State,Country,Email,InstitutionID")] Person input)
        {
            if (ModelState.IsValid)
            {
                Person person = await _context.People.FirstOrDefaultAsync(p => p.PersonID == PersonID);
                person.FirstName = input.FirstName;
                person.FamilyName = input.FamilyName;
                person.Affiliation = input.Affiliation;
                person.City = input.City;
                person.State = input.State;
                person.Country = input.Country;
                person.Email = input.Email;
                person.InstitutionID = input.InstitutionID;

                _context.Update(person);
                await _context.SaveChangesAsync();

                HttpContext.Session.SetInt32(nameof(Person.PersonID), person.PersonID);
                HttpContext.Session.SetString(nameof(Person.FirstName), person.FirstName);
                if (person.IsAdmin)
                    HttpContext.Session.SetString(nameof(Person.FamilyName), person.FamilyName);

                return RedirectToAction(nameof(HomeController.Success), "Home", new { message = "Update profile" });
            }
            ViewData["InstitutionID"] = new SelectList(_context.Institutions, "ABN", "Name", input.InstitutionID);
            return View(input);
        }

        public IActionResult Password() => View();

        public IActionResult Password(string password)
        {
            if (string.IsNullOrEmpty(password) || password.Length < 6)
                ModelState.AddModelError(nameof(password), "Password too short.");
            if (string.IsNullOrEmpty(password) || password.Length > 50)
                ModelState.AddModelError(nameof(password), "Password too Long.");
            if (!ModelState.IsValid)
                return View();
            _context.Logins.First(x => x.PersonID == PersonID).NewPassword(password);
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(HomeController.Success), "Home", new { message = "Update Password" });
        }


    }
}

DataSpace/DataSpace/Views/Shared/Statuscode.cshtml
@model Int32
@{
    ViewData["Title"] = "StatusCode";
}

<h1>@Model.ToString() Error</h1>

DataSpace/DataSpace/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Seccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Message"] Success</h1>
<div>
    <a asp-action="Index" class="btn btn-primary">Back to Home</a>
</div>

DataSpace/DataSpace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataSpace</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataSpace</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Person.PersonID)).HasValue;
                            var lastname = Context.Session.GetString(nameof(Person.FamilyName));
                            var name = Context.Session.GetString(nameof(Person.FirstName));
                            var isAdmin = !String.IsNullOrEmpty(lastname);
                            if (isAdmin)
                            {
                                name = name + " " + lastname;
                            }


                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Welcome,
                                </span>
                            </li>
                            @if (isAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Administrator</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">@name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DataSpace - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>